// <auto-generated />
using FakeZuydInlog.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FakeZuydInlog.Migrations
{
    [DbContext(typeof(FakeZuydInlogContext))]
    [Migration("20230413095233_inloginfo")]
    partial class inloginfo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FakeZuydInlog.Models.Inlog", b =>
                {
                    b.Property<string>("Gebruikersnaam")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Wachtwoord")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Gebruikersnaam");

                    b.ToTable("Inlog");
                });
#pragma warning restore 612, 618
        }
    }
}
